name: Bot 'Tezos'
on:
  push:
    branches:
      - tezos-js

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieving coin apps
        uses: actions/checkout@v2
        with:
          repository: LedgerHQ/coin-apps
          token: ${{ secrets.PAT }}
          path: coin-apps
      - uses: actions/setup-node@master
        with:
          node-version: 14.x
          cache: yarn
      - name: pull docker image
        run: docker pull ghcr.io/ledgerhq/speculos
      - name: kill apt-get
        run: sudo killall -w apt-get apt || echo OK
      - name: Install linux deps
        run: sudo apt-get install -y libusb-1.0-0-dev jq
      - name: Install dependencies
        run: |
          yarn global add yalc
          yarn --frozen-lockfile
          yarn ci-setup-cli
      - name: BOT
        env:
          SHOW_LEGACY_NEW_ACCOUNT: "1"
          DEBUG_HTTP_RESPONSE: "1"
          SEED: ${{ secrets.SEED4 }}
          VERBOSE_FILE: bot-tests.txt
          GITHUB_SHA: ${GITHUB_SHA}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          SLACK_CHANNEL: ci-xtz-ll
          BOT_FILTER_FAMILY: tezos
          EXPERIMENTAL_EXPLORERS: true
          EXPERIMENTAL_CURRENCIES_JS_BRIDGE: tezos
        run: COINAPPS=$PWD/coin-apps yarn ci-test-bot
        timeout-minutes: 120
      - name: Run coverage
        if: failure() || success()
        run: CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} npx codecov
      - name: upload logs
        if: failure() || success()
        uses: actions/upload-artifact@v1
        with:
          name: bot-tests.txt
          path: bot-tests.txt
